name: IP Scraper with Selenium

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间午夜运行
  workflow_dispatch:     # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-22.04  # 使用稳定的Ubuntu 22.04环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整git历史（用于后续提交）

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'  # 启用pip缓存加速安装

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip google-chrome-stable

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install \
          requests \
          beautifulsoup4 \
          geoip2 \
          selenium \
          webdriver-manager

    - name: Verify installations
      run: |
        echo "Chrome version: $(google-chrome --version)"
        python -c "
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        options = Options()
        options.add_argument('--headless')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        options.add_argument('--user-data-dir=/tmp/chrome-profile')
        driver = webdriver.Chrome(options=options)
        print('✅ ChromeDriver test successful!')
        driver.quit()
        "

    - name: Run scraping script
      run: python scrape_ips.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: ip-list
        path: ip.txt

    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ip.txt
        git commit -m "Auto-update IP list [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
