name: IP Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        pip install selenium webdriver-manager beautifulsoup4 geoip2 requests

    - name: Run scraper
      run: |
        python scrape_ips.py || [ $(wc -l < ip.txt || echo 0) -ge 10 ]  # 至少10个IP才算成功
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
