name: IP Scraper

on: 
  schedule: 
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  # 最小化权限控制

jobs:
  scrape:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.9"

      - name: Install Stack
        run: |
          sudo apt-get install -y google-chrome-stable
          pip install requests beautifulsoup4 selenium webdriver-manager

      - name: Verify Chrome
        run: |
          python -c "
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          options = Options()
          options.add_argument('--headless --no-sandbox --disable-dev-shm-usage')
          webdriver.Chrome(options=options).quit()
          print('✓ Chrome ready')
          "

      - name: Scrape & Commit
        run: |
          python scrape_ips.py
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ip.txt && git commit -m "Update IPs" && git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
