name: Scrape IPs with Selenium

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 geoip2 selenium

    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version

    - name: Install ChromeDriver
      run: |
        # 获取 Chrome 的完整版本号（例如 134.0.6998.165）
        CHROME_FULL_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        echo "Chrome 完整版本: $CHROME_FULL_VERSION"
        # 获取 Chrome 的主版本号（例如 134.0.6998）
        CHROME_MAJOR_VERSION=$(echo $CHROME_FULL_VERSION | grep -oP '\d+\.\d+\.\d+')
        echo "Chrome 主版本: $CHROME_MAJOR_VERSION"
        # 优先使用主版本号查询 ChromeDriver 版本
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION)
        # 检查 CHROMEDRIVER_VERSION 是否有效（不包含 XML 错误消息）
        if echo "$CHROMEDRIVER_VERSION" | grep -q "NoSuchKey"; then
          echo "未找到与 Chrome 主版本 $CHROME_MAJOR_VERSION 匹配的 ChromeDriver，尝试完整版本 $CHROME_FULL_VERSION..."
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_FULL_VERSION)
        fi
        # 如果仍然无效，使用默认版本
        if echo "$CHROMEDRIVER_VERSION" | grep -q "NoSuchKey" || [ -z "$CHROMEDRIVER_VERSION" ]; then
          echo "未找到匹配的 ChromeDriver 版本，使用默认版本 114.0.5735.90..."
          CHROMEDRIVER_VERSION="114.0.5735.90"
        fi
        echo "ChromeDriver 版本: $CHROMEDRIVER_VERSION"
        # 下载 ChromeDriver
        wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    - name: Run script
      run: python scrape_ips.py

    - name: Upload ip.txt as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ip-list
        path: ip.txt

    - name: Commit and push ip.txt to repository
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add ip.txt
        git commit -m "Update ip.txt with latest IPs"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
