name: IP Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        pip install selenium webdriver-manager

    - name: Verify Chrome
      run: |
        python -c "
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        options = Options()
        options.add_argument('--headless')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        options.add_argument('--user-data-dir=/tmp/chrome-$(date +%s)')  # 动态唯一路径
        driver = webdriver.Chrome(options=options)
        print('✅ Chrome ready!')
        driver.quit()
        "

    - name: Run script
      run: python scrape_ips.py
