name: IP Scraper with Selenium

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager

    - name: Verify Chrome installation
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        echo "Chrome version: $(google-chrome --version)"

    - name: Test ChromeDriver
      run: |
        python -c "
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        options = Options()
        options.add_argument('--headless')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        options.add_argument('--user-data-dir=/tmp/chrome-ci-profile')
        driver = webdriver.Chrome(options=options)
        print('✅ ChromeDriver test passed!')
        driver.quit()
        "

    - name: Run main script
      run: python scrape_ips.py
